name: "Build stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  artefact:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          export BUILD_DATETIME=${{ inputs.build_datetime }}
          make build
